#!/usr/bin/env python
"""Push the current working tree to the private Hugging Face code repo.

    python scripts/push_to_hf.py --token hf_xxx
    HF_TOKEN=hf_xxx python scripts/push_to_hf.py

Why this exists
---------------
The Kaggle notebooks pull the pipeline from a private HF repo rather than
from GitHub, because the repo is private and Kaggle has no SSH key. That
means the HF copy is a *snapshot*, and a snapshot goes stale the moment you
change anything locally. Running a benchmark against a stale snapshot is
worse than not running one: the numbers look real, and they describe code
you are no longer writing.

So this script exists to make re-pushing a one-liner, and the notebook
refuses to proceed unless the modules it expects are actually present in
what it downloaded (see the freshness check in
``kaggle/drishti3d_full_test.py``).

What is uploaded
----------------
Source only: ``drishti3d/``, ``scripts/``, ``tests/``, ``kaggle/`` and the
project files needed to install and run. Never the virtualenv, build
artefacts, model weights, videos or result directories -- those are
gigabytes, they are not source, and several of them are regenerated by the
very run that would download them.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Directories and patterns that must never reach the code repo. Weights and
# footage live in the *dataset* repo; everything else here is either
# derived, machine-local, or enormous.
IGNORE_PATTERNS = [
    ".venv/**",
    ".git/**",
    "build/**",
    "dist/**",
    "output/**",
    "results/**",
    "slide_assets/**",
    # Both forms of each cache pattern on purpose: `**/x/**` matches a
    # NESTED x/ but not a top-level one, so without the bare `x/**` twin
    # the caches at the repo root sail straight through.
    "__pycache__/**",
    "**/__pycache__/**",
    ".pytest_cache/**",
    "**/.pytest_cache/**",
    ".ruff_cache/**",
    "**/.ruff_cache/**",
    ".DS_Store",
    "**/.DS_Store",
    "*.mp4",
    "*.MP4",
    "*.mov",
    "*.MOV",
    "*.las",
    "*.ply",
    "*.glb",
    "*.obj",
    "*.zip",
    "*.pt",
    "*.pth",
    "*.safetensors",
]

# Modules the Kaggle notebook checks for. Listed here too so a push that
# would produce a snapshot the notebook rejects fails *before* uploading
# rather than after.
REQUIRED = [
    "drishti3d/semantics/segmenter.py",
    "drishti3d/semantics/labelling.py",
    "drishti3d/semantics/classes.py",
    "drishti3d/fusion/texture.py",
    "drishti3d/fusion/completion.py",
    "drishti3d/export/terrain.py",
    "drishti3d/export/depthviz.py",
    "drishti3d/ingest/photometric.py",
    "drishti3d/pipeline/stages.py",
    "drishti3d/device.py",
]


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Push source to the private HF code repo.")
    parser.add_argument("--repo-id", default="ajt0704/3chakshu", help="HF repo id (default: ajt0704/3chakshu).")
    parser.add_argument("--repo-type", default="model", choices=["model", "dataset"])
    parser.add_argument(
        "--token",
        default=None,
        help=(
            "HF write token. Defaults to $HF_TOKEN, then to the token cached by "
            "`huggingface-cli login`. Never hard-code this."
        ),
    )
    parser.add_argument("--message", default="Sync working tree for Kaggle benchmark")
    parser.add_argument("--dry-run", action="store_true", help="List what would upload, then stop.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = Path(__file__).resolve().parent.parent

    missing = [p for p in REQUIRED if not (root / p).exists()]
    if missing:
        print("refusing to push: these modules are missing from the working tree:", file=sys.stderr)
        for p in missing:
            print(f"  {p}", file=sys.stderr)
        return 1

    if args.dry_run:
        print(f"would upload {root} -> {args.repo_id} ({args.repo_type})")
        print("\nignoring:")
        for pattern in IGNORE_PATTERNS:
            print(f"  {pattern}")
        print(f"\nall {len(REQUIRED)} required modules present")
        return 0

    from huggingface_hub import HfApi, get_token, whoami

    # Resolution order: explicit flag, then $HF_TOKEN, then whatever
    # `huggingface-cli login` cached. The cached login is the common case --
    # requiring the token on the command line every time invites pasting it
    # into shell history, and from there into a screenshot or a repo.
    token = args.token or os.environ.get("HF_TOKEN") or get_token()
    if not token:
        print(
            "error: no token found.\n"
            "  Either run:  huggingface-cli login\n"
            "  or pass:     --token hf_xxx\n"
            "  or set:      HF_TOKEN=hf_xxx",
            file=sys.stderr,
        )
        return 1

    try:
        user = whoami(token=token)
        print(f"authenticated as {user.get('name')}")
    except Exception as exc:  # noqa: BLE001
        print(f"error: token rejected by Hugging Face ({type(exc).__name__}).", file=sys.stderr)
        return 1

    api = HfApi()
    print(f"uploading {root} -> {args.repo_id} ({args.repo_type})...")
    api.upload_folder(
        folder_path=str(root),
        repo_id=args.repo_id,
        repo_type=args.repo_type,
        token=token,
        commit_message=args.message,
        ignore_patterns=IGNORE_PATTERNS,
    )
    print("done. The Kaggle notebook's freshness check should now pass.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
